### PR TITLE
API docs correction for Functions hydrate_to: "use hydrate_to" can now read and link as "use hydrate".

### LINKED ISSUE #578: API docs correction for Functions hydrate_to: "use hydrate_to" should read and link as "use hydrate"
In https://docs.rs/sycamore/latest/sycamore/ under Functions hydrate_to it currently reads and links as: 
"Render a [View](https://docs.rs/sycamore/latest/sycamore/view/struct.View.html) under a parent node by reusing existing nodes (client side hydration). For rendering under the \<body> tag, use **hydrate_to** (https://docs.rs/sycamore/latest/sycamore/fn.hydrate_to.html) instead."

It should read and link as:
"Render a [View](https://docs.rs/sycamore/latest/sycamore/view/struct.View.html) under a parent node by reusing existing nodes (client side hydration). For rendering under the \<body> tag, use **hydrate** (https://docs.rs/sycamore/latest/sycamore/fn.hydrate.html) instead."

### PR DESCRIPTION
**Pull request by StarSapien**
API Docs fix #578.

### CODE REVIEW

**Comment by lukechu10** [comment]
This looks good. Is there a reason why you closed this?

**Comment by StarSapien** [comment]
I thought it was done. Was I not supposed to close it?

Nobody's ever asked me to do a PR before. I'm a PR virgin. I'm trying to lose my PR virginity.

Can I still save this attempt?

**Comment by StarSapien** [comment]
I've restored my branch and reopened my PR. I hope that helps.

Please let me know if there is anything else I should / shouldn't do.

**Comment by StarSapien** [comment]
It looks done. Should I do anything else now besides saying thank you for this great project?

**Pull request merged**
