### PR TITLE
Router example

### PR DESCRIPTION
**Pull request by davidon-top**
I was going to tackle the remaining 0.9 issues, half of which are router related, and i noticed that there is no example using router (which would be useful for router development).

### CODE REVIEW

**Review by lukechu10 — APPROVED** [review]
LGTM Thanks!

**Comment by lukechu10** [comment]
Wait actually could you add an entry to `examples/README.md`

**Comment by davidon-top** [comment]
good call, forgot about that

**Review by lukechu10 — APPROVED** [review]
Awesome!

**Pull request merged**
