### PR TITLE
Builder API

### PR DESCRIPTION
**Pull request by jquesada2016**
I have not fully tested, nor do I think the current iteration has the right aesthetics, but I believe it's in the right direction! This is an implementation attempt for the builder API as mentioned in #268.

### CODE REVIEW

**Comment by jquesada2016** [comment]
@lukechu10 All tests should pass. I went through the logs and adjusted some code to run on rustc v1.53, but it seems the tests did not re-run. Not sure why. Also, API is stable enough for an initial audit. I've migrated our project to use the API as it currently stands and have no issues. Parts that remain untested are the `styles` functions, since we aren't using styles. I will also be adding docs to the functions.

**Comment by lukechu10** [comment]
Wow thanks for all the work. I'll try to get to this soon.

**Comment by jquesada2016** [comment]
Would you like to try to aim this feature for `v0.7.0`?

**Comment by lukechu10** [comment]
Yes. That sounds good.

**Comment by lukechu10** [comment]
> No problem! I'm going to be mostly MIA the next couple weeks due to traveling. But I'll try to work on this whenever I get a chance.

No worries!



> What I was thinking was eventually making this a public macro which users could use for extending the builder API to use custom typed tags, which would be very useful for quickly adding support for something like Svelte Native, along with web components UI frameworks. Also, since this is a very simple macro, it didn't merit, in my opinion, dropping to a full procedural macro.

What I meant was
```rust
generate_tag_functions! { enum HtmlTag { ... } }
```
instead of
```rust
#[apply(generate_tag_functions)]
enum HtmlTag { ... }
```
because they are equivalent.



> Sure, we can remove these, though I can imagine some workflows, especially with dynamic tables or virtual lists where this kind of optimization could be useful. Perhaps mark the function as unsafe? (though this might break the builder flow) If not, I'm fine with removing it.

We might be able to do something about this with type-states but I think that belongs in another PR.

**Comment by lukechu10** [comment]
If you don't mind, I can merge this now and fix the issues I mentioned in a later PR to not make this one too long.

**Comment by jquesada2016** [comment]
Go right ahead!

**Pull request merged**
