### PR TITLE
Derived `Clone` for router types

### LINKED ISSUE #230: `Segment` should implement `Clone`
**Describe the bug**
The [`Segment`](https://docs.rs/sycamore-router/0.5.2/sycamore_router/enum.Segment.html) type in `sycamore-router` should implement `Clone` for convenience of working with the routing internals.

**To Reproduce**
Try cloning any `Segment`. In my case it was through `.to_vec()` on a `Vec<Segment>`.

**Expected behavior**
`Segment` should implement `Clone`.

**Environment**

- Sycamore: v0.5.2

### PR DESCRIPTION
**Pull request by arctic-hen7**
This just derives the `Clone` trait for the sycamore-router types `Segment`, `Capture`, and `RoutePath`, which makes it much easier to work with the routing internals. This is different to #231 in that it operated on `v0.5.2` instead of `master`!

This fixes #230.

### CODE REVIEW

**Comment by arctic-hen7** [comment]
If this could be pushed before the rest of the changes currently on `master`, that would be really great!

**Comment by lukechu10** [comment]
I hope to release 0.6 soon so this will be part of the next release.

**Comment by lukechu10** [comment]
lgtm, thanks for contributing!

**Comment by arctic-hen7** [comment]
Fantastic, thanks! My pleasure, all three lines!

**Pull request merged**
